---
collections:
  - name: vultr.cloud
    version: 1.9.0

roles:
  - name: galaxy.vultr_cloud
    src: ngine_io.vultr_cloud
    version: v0.2.0
  - name: galaxy.nginx
    src: geerlingguy.nginx
    version: 3.1.4
