---
- hosts: web
  roles:
    - role: galaxy.nginx
  tasks:
    - name: Allow all access http/s
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - "80"
        - "443"
